<img src="logo.png">

Supongamos que somos un agente de Airbnb localizado en CDMX, y tenemos que atender peticiones de varios clientes. Tenemos un archivo llamado airbnb_cdmx.csv donde tenemos información de todos los alojamientos de Airbnb en CDMX

In [2]:
import numpy as np
import pandas as pd

In [4]:
airbnb = pd.read_csv("C:/Users/hp master/Documents/SciData/Py_CDD/airbnb_cdmx.csv")
airbnb

id    host_id neighbourhood_cleansed property_type  \
0         35797     153786  Cuajimalpa de Morelos         Villa   
1         56074     265650             Cuauhtemoc   Condominium   
2         61792     299558             Cuauhtemoc         House   
3         70644     212109               Coyoacan     Apartment   
4        107078     540705         Miguel Hidalgo          Loft   
...         ...        ...                    ...           ...   
21819  43856289   63979434             Cuauhtemoc         House   
21820  43856833   35255741             Cuauhtemoc     Apartment   
21821  43858230   85020390         Alvaro Obregon     Apartment   
21822  43858765  264767749             Cuauhtemoc     Apartment   
21823  43859282  139156115         Miguel Hidalgo   Condominium   

             room_type  accommodates  price  minimum_nights  maximum_nights  \
0      Entire home/apt             2   4500               1               7   
1      Entire home/apt             3    843               4             150   
2         Private room             2   1359               2              21   
3      Entire home/apt             2   1245               6             180   
4      Entire home/apt             2   4868               4             365   
...                ...           ...    ...             ...             ...   
21819     Private room             4    996               1              15   
21820  Entire home/apt             8   1766               2              35   
21821  Entire home/apt             3    990               3            1125   
21822  Entire home/apt             2   1109               1            1125   
21823  Entire home/apt             2    566              90             365   

       bedrooms  beds          cancellation_policy  number_of_reviews  \
0           1.0   1.0                     flexible                  0   
1           1.0   2.0                     moderate                 60   
2           1.0   1.0                     moderate                 52   
3           1.0   1.0                     moderate                102   
4           1.0   1.0  strict_14_with_grace_period                 10   
...         ...   ...                          ...                ...   
21819       1.0   3.0                     flexible                  0   
21820       3.0   8.0  strict_14_with_grace_period                  0   
21821       3.0   3.0  strict_14_with_grace_period                  0   
21822       1.0   1.0                     flexible                  0   
21823       1.0   1.0                     flexible                  0   

       review_scores_accuracy  
0                         NaN  
1                        10.0  
2                        10.0  
3                        10.0  
4                        10.0  
...                       ...  
21819                     NaN  
21820                     NaN  
21821                     NaN  
21822                     NaN  
21823                     NaN  

[21824 rows x 14 columns]

En concreto el dataset tiene las siguientes variables:

* id: el identificador de la propiedad
* host_id: el identificador del dueño de la propiedad
* neighborhood_cleansed: alcaldía en CDMX
* property_type: tipo de propiedad 
* room_type: tipo de habitación
* accommodates: El numero de personas que se pueden alojar en la propiedad price: precio (en pesos mexicanos)
* minimum_nights, maximum_nights: mínimo y máximo de noches
* bedrooms: El número de habitaciones
* beds: número de camas
* cancellation_policy: política de cancelación
* number_of_reviews: El numero de opiniones
* review_scores_accuracy: Puntuacion media del apartamento

# Alicia y su familia

Alicia va a ir a CDMX durante una semana con su marido y sus 2 hijos. Están buscando un apartamento con habitaciones separadas para los padres y los hijos. No les importa donde alojarse o el precio, simplemente quieren tener una experiencia agradable. Esto significa que solo aceptan lugares con más de 10 críticas con una puntuación mayor de 4. Cuando seleccionemos habitaciones para Alicia, tenemos que asegurarnos de ordenar las habitaciones de mejor a peor puntuación. Para aquellas habitaciones que tienen la misma puntuación, debemos mostrar antes aquellas con más críticas. Debemos a lo más la tercera parte del total de posibilidades.

In [24]:
# num_noches = 6
# num_habitaciones > 1
# num_criticas > 10
# puntuacion > 4

# Ordenar las habitaciones de mejor a peor puntuación; con la misma puntuación, mostramos primero aquellas con mas crítcas.
# Mostrar 

airbnb[(airbnb["minimum_nights"] == 6) & (airbnb["bedrooms"] > 1) & 
       (airbnb["number_of_reviews"] > 10) & (airbnb["review_scores_accuracy"] > 4)].sort_values(
    by =["review_scores_accuracy","number_of_reviews"],ascending = [False,False]).head(5)


id   host_id neighbourhood_cleansed property_type  \
2998  14746939  91876146               Coyoacan         House   
9393  27491509  21943018             Cuauhtemoc     Apartment   
4997  19106691  18473469             Cuauhtemoc     Apartment   
3170  15209492  68157735             Cuauhtemoc     Apartment   
170    1337735   6775211         Miguel Hidalgo     Apartment   

            room_type  accommodates  price  minimum_nights  maximum_nights  \
2998  Entire home/apt             4   1585               6              28   
9393  Entire home/apt             5   1042               6            1125   
4997  Entire home/apt            12   2241               6            1125   
3170  Entire home/apt             6   3736               6              28   
170   Entire home/apt             4   2151               6            1125   

      bedrooms  beds          cancellation_policy  number_of_reviews  \
2998       2.0   2.0  strict_14_with_grace_period                 63   
9393       2.0   3.0                     flexible                 53   
4997       6.0   6.0  strict_14_with_grace_period                 52   
3170       3.0   4.0  strict_14_with_grace_period                 46   
170        2.0   2.0                     moderate                 44   

      review_scores_accuracy  
2998                    10.0  
9393                    10.0  
4997                    10.0  
3170                    10.0  
170                     10.0

## Roberto contra su hermana

Roberto es un casero que tiene una casa en Airbnb. De vez en cuando nos llama preguntando sobre cuales son las críticas de su alojamiento. Hoy está particularmente molesto, ya que su hermana Valentina ha puesto una casa en Airbnb y Roberto quiere asegurarse de que su casa tiene más críticas que las de Valentina. Tenemos que crear un dataframe con las propiedades de ambos. Las id de las casas de Roberto y Valentina son 43856289 y 107078 respectivamente. 

In [30]:
airbnb[(airbnb["id"] == 43856289) | (airbnb["id"] == 107078)]

id   host_id neighbourhood_cleansed property_type  \
4        107078    540705         Miguel Hidalgo          Loft   
21819  43856289  63979434             Cuauhtemoc         House   

             room_type  accommodates  price  minimum_nights  maximum_nights  \
4      Entire home/apt             2   4868               4             365   
21819     Private room             4    996               1              15   

       bedrooms  beds          cancellation_policy  number_of_reviews  \
4           1.0   1.0  strict_14_with_grace_period                 10   
21819       1.0   3.0                     flexible                  0   

       review_scores_accuracy  
4                        10.0  
21819                     NaN

## Diana "la mochilera"

Diana va a CDMX a pasar 3 noches y quiere conocer a gente nueva. Tiene un presupuesto de 1,250 pesos mexicanos para su alojamiento. Debemos buscarle las 10 propiedades más baratas, dandole preferencia a aquellas que sean habitaciones compartidas, y para aquellas viviendas compartidas debemos elegir aquellas con mejor puntuación.

In [42]:
airbnb[(airbnb["minimum_nights"] == 3) & (airbnb["price"] < 1250/3) & (airbnb["room_type"] == "Shared room")].sort_values(by = ["price","review_scores_accuracy"], ascending = [True,False]).head(10)

id    host_id neighbourhood_cleansed property_type    room_type  \
12068  32197684  229856606                Tlalpan         House  Shared room   
6345   21596500    2269083         Miguel Hidalgo     Apartment  Shared room   
3014   14798191   92432250         Miguel Hidalgo     Apartment  Shared room   
19435  41935600   48980196          Benito Juarez     Apartment  Shared room   
12376  32672455  223965193      Gustavo A. Madero     Apartment  Shared room   
14379  35612219   36162947             Cuauhtemoc     Apartment  Shared room   
7926   24183514  182277365             Cuauhtemoc     Apartment  Shared room   
2564   13514931   77600854         Alvaro Obregon          Loft  Shared room   
4667   18414203  127596584             Cuauhtemoc     Apartment  Shared room   
12323  32583561   27215085         Miguel Hidalgo         House  Shared room   

       accommodates  price  minimum_nights  maximum_nights  bedrooms  beds  \
12068             1    180               3            1125       1.0   1.0   
6345              1    181               3            1125       1.0   1.0   
3014              1    181               3              90       1.0   1.0   
19435             1    205               3            1125       1.0   1.0   
12376             2    248               3               4       1.0   1.0   
14379             1    249               3              90       1.0   1.0   
7926              2    272               3               7       1.0   1.0   
2564              2    361               3              15       1.0   2.0   
4667              2    362               3               4       1.0   2.0   
12323             2    385               3            1125       1.0   2.0   

               cancellation_policy  number_of_reviews  review_scores_accuracy  
12068                     moderate                  1                    10.0  
6345                      flexible                  2                    10.0  
3014   strict_14_with_grace_period                 26                     9.0  
19435                     moderate                  1                    10.0  
12376                     flexible                  0                     NaN  
14379                     moderate                  8                    10.0  
7926                      flexible                  1                    10.0  
2564                      flexible                  0                     NaN  
4667                      flexible                  0                     NaN  
12323  strict_14_with_grace_period                 11                    10.0

In [33]:
airbnb["room_type"].unique()

array(['Entire home/apt', 'Private room', 'Hotel room', 'Shared room'],
      dtype=object)